#!/bin/sh

# Palaist polybar un termināļa krāsas un konfigurācijas
sh ~/.config/polybar/launch.sh
sh ~/rt.sh

export SXHKD_SHELL=/bin/sh
# Uzstādīt fona attēlu
feh --bg-scale ~/Pictures/38580.jpg &

# Aktivizēt kompozitoru
picom &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         3
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Izskata modifikācijas
bspc config normal_border_color "#2D2D2D"
bspc config focused_border_color "#1ABB9B"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"
bspc config presel_feedback_color "#1ABB9B"

sxhkd -f 100 &
